### PR TITLE
Library Porting Completed

### PR DESCRIPTION
**Pull request by amaresh91**

### CODE REVIEW

**Review by GowthamRayar — DISMISSED** [review]
Done 1st round of review for Library code

**Review by GowthamRayar — DISMISSED** [review]
Reviewed CheckStyle And SonarQube Task

**Review by GowthamRayar — DISMISSED** [review]
Code Review done

**Review by GowthamRayar — DISMISSED** [review]

**Review by sharathks84 — APPROVED** [review]
Okay approved. In next iteration we should remove the duplicate lines

**Pull request merged**
